//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouroboros.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysAction()
        {
            this.IsDeleted = false;
            this.SysUserAction = new HashSet<SysUserAction>();
            this.SysRole = new HashSet<SysRole>();
        }
    
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string ActionCode { get; set; }
        public Ouroboros.Model.EnumList.ActionType ActionType { get; set; }
        public int ParentId { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Ouroboros.Model.EnumList.HttpMethodType HttpMethd { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserAction> SysUserAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysRole> SysRole { get; set; }
    }
}
