//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouroboros.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysUserAction()
        {
            this.IsDeleted = false;
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ActionId { get; set; }
        public bool HasPermission { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SysUser SysUser { get; set; }
        public virtual SysAction SysAction { get; set; }
    }
}
